### ISSUE TITLE
Бамплимит

### ISSUE THREAD

**Issue by fadedDexofan** [anonim-legivon/picoboard#4]
* Сделать таск в Celery и настроить celery beat для автоудаления тредов в бамплимите

Возможно стоит не удалять треды и посты целиком, а помечать их удаленными используя https://github.com/jazzband/django-model-utils
Это позволит сделать архив и через воркер удалять только треды старше определенного времени

**Comment by AndreiDrang** [comment]
В теории можно ж просто треду прикрутить choice с состояниями и все на этом. Не юзая доп.бибилиотеки.
Ну и потом в через celery менять статус треда(по сроку давности) и в том же целери раз в день(под утро по МСК) проверять наличие совсем старых тредов в архиваче и удалять их(а может не стоит удалять из архива? А стоит переносить просто в другую БД и другой сервак)
